article/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
app_name = "article"

urlpatterns = [
    path("",views.articles,name="articles"),
    path("articles2/",views.articles2,name="articles2"),
    path("addarticle/",views.addarticle,name="addarticle"),
    path("article/<int:id>",views.detail,name="detail"),
    path("dashboard/",views.dashboard,name="dashboard"),
    path("update/<int:id>",views.update,name="update"),
    path("delete/<int:id>",views.delete,name="delete"),
    path("comment/<int:id>",views.addcomment,name="comment"),
]

forum/urls.py
from django.contrib import admin
from django.urls import path,include
#MODELS
from article import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.index,name="name"),
    path("user/",include("user.urls")),
    path("about/",views.about,name="about"),
    path('articles/',include("article.urls")),
    path("user/",include("user.urls")),
    path("users",views.users,name="users"),
    path("news/",views.news,name="news"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from user import views

app_name="user"

urlpatterns = [
    path("login/",views.loginUser,name="login"),
    path("register/",views.register,name="register"),
    path("logout/",views.logoutUser,name="logout"),
]

article/models.py
from django.db import models
#ck editör
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

# Create your models here.

#makale oluşturma
class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Yazar ")
    title = models.CharField(max_length = 50,verbose_name = "Başlık  ")
    content = RichTextField(verbose_name="İçerik ")
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank = True,null = True,verbose_name="Makaleye Fotoğraf Ekleyin")

    def __str__(self):
        return self.title



#profil kısmı
class Customer(models.Model):
    user = models.OneToOneField(User,null = True,on_delete=models.CASCADE)
    name = models.CharField(max_length=40,null=True,verbose_name="Adınız ve Soyadınız")
    email = models.CharField(max_length=200,null=True,verbose_name="E-posta")
    date_created = models.DateTimeField(auto_now_add=True,null=True)
    profile = models.ImageField(default="user.png",null = True,blank = True,verbose_name="Profil Fotoğrafınız")

    def __str__(self):
        return self.name
    




#yorum ekleme
class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="Makale",related_name="comments")
    comment_author = models.CharField(max_length=50,verbose_name="İsim")
    comment_content = models.CharField(max_length=200,verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article
from .models import Customer
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image",]

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['user']

user/forms.py
#KAYIT FORMLARI BU KISMA GİRİLİYOR
#KAYIT FORMLARI
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from user import urls
from django.contrib.auth.models import User


class RegisterForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={"class": "input-text","placeholder":"Kullanıcı Adı"}
    ),required=True,max_length=50)

    email = forms.CharField(widget=forms.EmailInput(
        attrs={"class":"input-text","placeholder":"Email"}
    ),required=True,max_length=50)

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={"class":"input-text","placeholder":"Şifre"}
    ),required=True,max_length=50)

    class Meta():
        model = User
        fields = ["username","email","password"]

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        email = self.cleaned_data.get("email")

        values = {
            "username" : username,
            "password" : password,
            "email":email,
            
        }
        return values

class LoginForm(forms.Form):
    username = forms.CharField(label = "Kullanıcı Adı")
    password = forms.CharField(label = "Parola",widget = forms.PasswordInput)

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from .models import Article,Comment,Customer
from .forms import ArticleForm,CustomerForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


from forum import urls
# Create your views here.


def index(request):
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")










def detail(request,id):
    article = get_object_or_404(Article,id=id)
    comments = article.comments.all()

    return render(request,"detail.html",{"article":article,"comments":comments})


def news(request):
    return render(request,"news.html")


def addcomment(request,id):
    article = get_object_or_404(Article,id=id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author=comment_author,comment_content=comment_content)

        newComment.article = article

        newComment.save()
    return redirect("/articles/article/" + str(id))







@login_required(login_url="user:login")
def addarticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        
        article.author = request.user
        article.save()

        messages.success(request,"Makale başarıyla oluşturuldu")
        return redirect("article:articles")
    return render(request,"addarticle.html",{"form":form})


#######################################################


    

def articles2(request):
    if request.user.is_authenticated == False:
        articles = Article.objects.all()
        keyword = request.GET.get("keyword")
        if keyword:
            articles = Article.objects.filter(title__contains = keyword)
            return render(request,"articles.html",{"articles":articles})
        return render(request,"articles2.html",{"articles":articles})
    return render(request,"articles2.html")


def articles(request):
    if request.user.is_authenticated == False:
        return redirect("/articles/articles2")
        messages.error(request,"Projelere Erişmek İçin Lütfen Giriş Yapınız")
        
    if request.user.is_authenticated == True:
        articles = Article.objects.all()
        keyword = request.GET.get("keyword")
        if keyword:
            articles = Article.objects.filter(title__contains = keyword)
            return render(request,"articles.html",{"articles":articles})

        return render(request,"articles.html",{"articles":articles})

    else:
        articles = Article.objects.all()
        articles = Article.objects.filter(author=request.user)
        context = {
            "articles":articles,
        }
    
    return render(request,"articles.html",context)


@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author=request.user)
    context = {
        "articles":articles
    }
    return render(request,"dashboard.html",context)

@login_required(login_url = "user:login")
def update(request,id):
    article = get_object_or_404(Article, id = id)
    form = ArticleForm(request.POST or None, request.FILES,instance=article)
    if form.is_valid():
        article = form.save(commit=False)

        article.author = request.user
        article.save()
        messages.success(request,"Makale Başarıyla Güncellendi")
        return redirect("articles/dashboard")
    return render(request,"update.html", {"form":form})

def delete(request,id):
    article = get_object_or_404(Article,id = id)
    article.delete()
    messages.success(request,"Makaleniz Başarıyla Silindi")
    return redirect("/articles/dashboard")

@login_required(login_url = "user:login")
def users(request):
    articles = Article.objects.filter(author=request.user)
    customer = request.user.customer
    form = CustomerForm(instance=customer)
    if request.method =="POST":
        form = CustomerForm(request.POST,request.FILES,instance = customer)
        if form.is_valid():
            form.save()

    
    context = {
        "form":form,
        "articles":articles,
    }
    return render(request,"users.html",context)
    

user/views.py
from django.shortcuts import render,redirect

#Modeller
from .forms import RegisterForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.shortcuts import render,redirect
from django.contrib.auth import login, authenticate,logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
from django.contrib.auth import authenticate
from .forms import LoginForm



def register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        newUser = User(username = username)
        newUser.set_password(password)

        newUser.save()
        login(request,newUser)
        messages.info(request,"Başarıyla Kayıt Olundu")

        return redirect("/articles")
    context = {
        "form": form
    }

    return render(request,"register.html",context)



def loginUser(request):
    form = LoginForm(request.POST or None)

    context = {
        "form":form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        

        user = authenticate(username = username,password = password )

        if user is None:
            messages.info(request,"Kullanıcı Adı veya Parola Hatalı")
            return render(request,"login.html",context)

        messages.success(request,"Başarıyla Giriş Yaptınız")
        login(request,user)
        return redirect("/articles")
    return render(request,"login.html",context)







def logoutUser(request):
    logout(request)
    messages.success(request,"Başarıyla Çıkış Yaptınız")
    return redirect("/articles")

templates/articles.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<header class="masthead text-center text-white" style="color:white;">
    <div class="masthead-content">
      <div class="container">
        <h1 class="masthead-heading mb-0" style="color:white;">!TAB FORUM</h1>
        <h2 class="masthead-subheading mb-0">Kodların Olimposu</h2>
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>

<div class="alert alert-warning">Hoşgeldiniz, <small>{{request.user.username}}</small></div>
<a href="/articles/dashboard"><button class="btn btn-primary" style="margin-left:1%; margin-bottom:-3%;"> Konu Başlat</button></a>

{% if articles %}

<div class="container-fluid mt-100">
    <div class="d-flex flex-wrap justify-content-between">
        <form>
                 {% csrf_token %} 
                <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Ara...">
              <button type="submit" class="btn btn-danger">Ara</button>
            </form>>
    </div>
    <div class="card mb-3">
        <div class="card-header pl-0 pr-0">
            <div class="row no-gutters w-100 align-items-center">
                <div class="col ml-3">Gündemdekiler</div>
                <div class="col-4 text-muted">
                    <div class="row no-gutters align-items-center">
                        <div class="col-4">Sıra</div>
                        <div class="col-8">Tarih</div>
                    </div>
                </div>
            </div>
        </div>
        {% for article in articles  %}
        <div class="card-body py-3">
            <div class="row no-gutters align-items-center">
            
                <div class="col"> <a href="/articles/article/{{article.id}}" class="text-big" data-abc="true">{{article.title}}</a><span class="badge badge-success align-text-bottom ml-1" >Güncel</span>
                    <div class="text-muted small mt-1">{{article.created_date}} &nbsp;·&nbsp; <a href="javascript:void(0)" class="text-muted" data-abc="true">{{article.author}}</a></div>
                </div>
                <div class="d-none d-md-block col-4">
                    <div class="row no-gutters align-items-center">
                        <div class="col-4">{{article.id}}</div>
                        <div class="media col-8 align-items-center"> <img src="{{request.user.customer.profile.url}}" alt="" class="d-block ui-w-30 rounded-circle">
                            <div class="media-body flex-truncate ml-2">
                                <div class="line-height-1 text-truncate">{{article.created_date}}</div> <a href="javascript:void(0)" class="text-muted small text-truncate" data-abc="true">{{article.author}}</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr class="m-0">
        
        {% endfor %}
        <br><br>

        <nav>
        <ul class="pagination mb-5">
            <li class="page-item disabled"><a class="page-link" href="javascript:void(0)" data-abc="true">«</a></li>
            <li class="page-item active"><a class="page-link" href="javascript:void(0)" data-abc="true">1</a></li>
            <li class="page-item"><a class="page-link" href="javascript:void(0)" data-abc="true">2</a></li>
            <li class="page-item"><a class="page-link" href="javascript:void(0)" data-abc="true">3</a></li>
            <li class="page-item"><a class="page-link" href="javascript:void(0)" data-abc="true">»</a></li>
        </ul>
    </nav>
{% else %}
<br><br><br><br><br>
<div class="alert alert-danger">Böyle Bir Makale Bulunamadı</div>
{% endif %}
<br><br><br><br><br><br><br><br>

{% endblock body %}

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<br><br>
<div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">İçerik</div>
                            <a class="nav-link" href="/articles/dashboard">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Makale  Yönetim Paneli
                            </a>
                            <div class="sb-sidenav-menu-heading">Konu Başlat</div>
                            <a class="nav-link collapsed" href="/articles/addarticle" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Makale Ekle
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="sb-sidenav-menu-heading">Profil</div>
                            <a class="nav-link collapsed" href="/users" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Profil
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="layout-static.html"></a>
                                    <a class="nav-link" href="layout-sidenav-light.html"></a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                        
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="login.html">Login</a>
                                            <a class="nav-link" href="register.html">Register</a>
                                            <a class="nav-link" href="password.html">Forgot Password</a>
                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                        Error
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="401.html">401 Page</a>
                                            <a class="nav-link" href="404.html">404 Page</a>
                                            <a class="nav-link" href="500.html">500 Page</a>
                                        </nav>
                                    </div>
                                </nav>
                            </div>
                            <div class="sb-sidenav-menu-heading"></div>
                            <a class="nav-link" href="charts.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                
                            </a>
                            <a class="nav-link" href="tables.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                
                            </a>
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Yapım : </div>
                        OğuzKaanEkin
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid">
                        <h1 class="mt-4">Makale Yönetimi</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Makaleler</li>
                        </ol>
                        <div class="row">
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-primary text-white mb-4">
                                    <div class="card-body">Python</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">Güncellemeler Devam Etmektedir</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-warning text-white mb-4">
                                    <div class="card-body">JS</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">Güncellemeler Devam Etmektedir</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-success text-white mb-4">
                                    <div class="card-body">HTML</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">Güncellemeler Devam Etmektedir</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-danger text-white mb-4">
                                    <div class="card-body">CSS</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">Güncellemeler Devam Etmektedir</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-chart-area mr-1"></i>
                                        Kullanıcı : 
                                    </div>
                                    <div class="card-body">Hoşgeldiniz, <small style="color:red;">{{request.user.username}}</small><canvas id="myAreaChart" width="100%" height="40"></canvas></div>
                                </div>
                            </div>
                            <div class="col-xl-6">
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-chart-bar mr-1"></i>
                                        Oturum : 
                                    </div>
                                    <div class="card-body">
                                        <br><br><br>
                                        <form method="post" enctype = multipart/form-data>
                                            {% csrf_token %}
                                            {{form.as_p}}
                                            <input type="submit" class="btn btn-primary">
                                        </form>
                                    <canvas id="myBarChart" width="100%" height="40"></canvas></div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table mr-1"></i>
                                Makaleleriniz
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    {% if articles %}
                                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                            <tr>
                                                <th>id</th>
                                                <th>Başlık</th>
                                                <th>Yazar</th>
                                                <th>Tarih</th>
                                                <th>Güncelle</th>
                                                <th>Sil</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for article in articles %}
                                            <tr>
                                                <td>{{article.id}}</td>
                                                <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
                                                <td>{{article.author.username}}</td>
                                                <td>{{article.created_date}}</td>
                                                <td><a href="/articles/update/{{article.id}}" class = "btn btn-danger">Güncelle</a></td>
                                                <td><a href="/articles/delete/{{article.id}}" class = "btn btn-danger">Sil</a></td>
                                            </tr>
                                               {% endfor %}
                                        </tbody>
                                    </table>
                                    {% else %}
                                    <div class = "alert alert-danger">
                                        Henüz bir makaleniz bulunmuyor...
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </main>



<br>
{% endblock body %}

templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<header class="masthead text-center text-white" style="color:white;">
    <div class="masthead-content">
      <div class="container">
        <h1 class="masthead-heading mb-0" style="color:white;">!TAB FORUM</h1>
        <h2 class="masthead-subheading mb-0">Kodların Olimposu</h2>
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>
  
<div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4"> <span style = "color:red;">Konu :</span>  {{article.title}}</h1>

        <!-- Author -->
        <p class="lead">
          Yazar : 
          <a href="#">{{article.author}}</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p> Yazım Tarihi : {{article.created_date}}</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead">{{article.content|safe}}</p>
        
        <br><br><br>
        <hr>
        <h4>Yorumlar</h4>
        <hr>

        

        
      {% if comments %}
      {% for comment in comments  %}
      <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="{%static 'img/tab.jpg'%}" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.comment_author}}</h5>
            {{comment.comment_date}}
            {{comment.comment_content}}
          </div>
        </div>
      {% endfor %}
      

      {% else %}
      <div class="alert alert-danger">Bu makaleye herhangi bir yorum yazılmamış,İlk yorumu yapan siz olun</div>
      {% endif %}
        
        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Yorum Ekle:</h5>
          <div class="card-body">
            <form method = "post" action = "{% url 'article:comment' article.id %}">
              {% csrf_token %}
              <div class="form-group">
                  <label for="formGroupExampleInput">İsim</label>
                  <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi girin">
                </div>
              <div class="form-group">
                  <label for="formGroupExampleInput">Yorum</label>
                <textarea name = "comment_content" class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-danger">Ekle</button>
            </form>
          </div>
        </div>
        </div>
        
      </div>

        

        

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
         
        </div>

        

      </div>

    </div>
    <!-- /.row -->

  </div>

{% endblock body %}